controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    zoe_controller:
      type: zoe_controller/ZoeController

zoe_controller:
  ros__parameters:
    wheel_front_left: wheel_front_left_joint
    wheel_front_right: wheel_front_right_joint
    wheel_back_left: wheel_back_left_joint
    wheel_back_right: wheel_back_right_joint
    axle_yaw_front: axle_yaw_front_joint
    axle_yaw_back: axle_yaw_back_joint
    publish_rate: 50.0