controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    zoe_controller:
      type: zoe_controller/ZoeController

zoe_controller:
  ros__parameters:
    front_left_wheel: front_left_wheel_joint
    front_right_wheel: front_right_wheel_joint
    back_left_wheel: back_left_wheel_joint
    back_right_wheel: back_right_wheel_joint
    front_yaw: front_yaw_joint
    back_yaw: back_yaw_joint
    publish_rate: 50.0