<?xml version="1.0" encoding="UTF-8"?>
<!-- This macro defines the actual link-joint structure of the robot. -->
<!-- The macro can be called by other files via <xacro:zoe2 prefix="$(arg prefix)" > -->
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:include filename="$(find zoe2_description)/urdf/common/inertials.xacro" />
  <xacro:include filename="$(find zoe2_description)/urdf/common/materials.xacro" />

  <xacro:include filename="$(find zoe2_description)/urdf/common/wheel.xacro" />
  <xacro:include filename="$(find zoe2_description)/urdf/common/chassis.xacro" />
  <xacro:include filename="$(find zoe2_description)/urdf/common/axle.xacro" />
  <xacro:include filename="$(find zoe2_description)/urdf/common/hinge.xacro" />
  <xacro:include filename="$(find zoe2_description)/urdf/common/params.xacro" />

  <xacro:macro name="zoe2" params="prefix *origin">
    <!-- LINKS -->
    <link name = "${prefix}base_link">
    </link>

    <xacro:chassis name="${prefix}chassis" rpy="0 0 0" xyz="0 0 0" />

    <xacro:hinge name="${prefix}front_roll" rpy="${pi/2} 0 0" xyz="0 0 0" />

    <xacro:wheel name="${prefix}front_right_wheel" rpy="0 0 ${pi/2}" xyz="0 0 0" />

    <xacro:wheel name="${prefix}front_left_wheel" rpy="0 0 ${-pi/2}" xyz="0 0 0" />

    <xacro:axle name="${prefix}front_axle" rpy="${pi/2} 0 0" xyz="0 0 0" />

    <xacro:wheel name="${prefix}back_right_wheel" rpy="0 0 ${pi/2}" xyz="0 0 0" />

    <xacro:wheel name="${prefix}back_left_wheel" rpy="0 0 ${-pi/2}" xyz="0 0 0" />

    <xacro:axle name="${prefix}back_axle" rpy="${pi/2} 0 0" xyz="0 0 0" />

    <xacro:hinge name="${prefix}back_roll" rpy="${-pi/2} 0 0" xyz="0 0 0" />

    <!-- END LINKS -->

    <!-- JOINTS -->

    <joint name="${prefix}chassis_joint" type="fixed">
        <parent link="${prefix}base_link" />
        <child link="${prefix}chassis" />
        <origin xyz="0 0 ${wheel_radius}" />
    </joint>


    <joint name="${prefix}chassis_front_roll_joint" type="fixed">
        <parent link="${prefix}chassis" />
        <child link="${prefix}front_roll" />
        <origin xyz="0 ${-(robot_length/2 - robot_hinge_length)} 0" />
    </joint>

    <joint name="${prefix}front_yaw_joint" type="revolute"> 
        <parent link="${prefix}front_roll" />
        <child link="${prefix}front_axle" />
        <origin xyz="0 ${-robot_hinge_length} -0.075" />
        <axis xyz="0 0 1"/>
        <limit lower="${-front_vertical_limit}" upper="${front_vertical_limit}" effort="10" velocity="10"/>
    </joint>

    <joint name="${prefix}front_right_wheel_joint" type="continuous">
        <parent link="${prefix}front_axle" />
        <child link="${prefix}front_right_wheel" />
        <origin xyz="${robot_width/2} 0 0" />
        <axis xyz="1 0 0" />
    </joint>

    <joint name="${prefix}front_left_wheel_joint" type="continuous">
        <parent link="${prefix}front_axle" />
        <child link="${prefix}front_left_wheel" />
        <origin xyz="${-robot_width/2} 0 0" />
        <axis xyz="1 0 0" />
    </joint>

    <!-- temp set to fixed -->
    <joint name="${prefix}back_yaw_joint" type="revolute">
        <parent link="${prefix}back_roll" />
        <child link="${prefix}back_axle" />
        <origin xyz="0 ${robot_hinge_length} -0.075" />
        <limit lower="${-front_vertical_limit}" upper="${front_vertical_limit}" effort="10" velocity="10"/>
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="${prefix}back_right_wheel_joint" type="continuous">
        <parent link="${prefix}back_axle" />
        <child link="${prefix}back_right_wheel" />
        <origin xyz="${robot_width/2} 0 0" />
        <axis xyz="1 0 0" />
    </joint>

    <joint name="${prefix}back_left_wheel_joint" type="continuous">
        <parent link="${prefix}back_axle" />
        <child link="${prefix}back_left_wheel" />
        <origin xyz="${-robot_width/2} 0 0" />
        <axis xyz="1 0 0" />
    </joint>

    <!-- current roll joint limits set arbitrarily... -->
    <joint name="${prefix}chassis_back_roll_joint" type="revolute">
        <parent link="${prefix}chassis" />
        <child link="${prefix}back_roll" />
        <origin xyz="0 ${+(robot_length/2 - robot_hinge_length)} 0" />
        <limit lower="-0.5" upper="0.5" effort="10" velocity="10"/>
        <axis xyz="0 1 0" />
    </joint>

    <!-- END JOINTS -->

  </xacro:macro>
</robot>
