<?xml version="1.0"?>
    <robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">
    <!-- all are in meters -->
    <xacro:property name="robot_width" value="1.64" />
    <xacro:property name="robot_length" value="1.91"/>
    <xacro:property name="base_link_height" value="0.4"/>
    <!-- Chassis -->
    <xacro:property name="chassis_length" value="1.5"/>
    <xacro:property name="chassis_width" value="1.2"/>
    <xacro:property name="chassis_height" value="0.5"/>

    <!-- Hinge -->
    <xacro:property name="robot_hinge_length" value="0.2"/>
    <xacro:property name="front_vertical_limit" value="${pi/4}"/>
    <!-- Wheel -->
    <xacro:property name="wheel_radius" value="0.325"/>
    <xacro:property name="wheel_thickness" value="0.05"/>
    <!-- Axle -->
    <xacro:property name="axle_box_width" value="0.1"/>
    <xacro:property name="axle_length" value="${robot_width-wheel_thickness}"/>
    <xacro:property name="axle_drop" value="0.119"/>

    <!-- Speed limits -->
    <xacro:property name="max_wheel_speed" value="4.0"/>
</robot>